"""Report exporters."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

from .models import RepoRecord
from .normalizers import compact_text


def write_markdown(
    path: str | Path,
    repos: list[RepoRecord],
    site_url: str,
    *,
    run_status: str = "complete",
    stats: dict[str, int] | None = None,
    notes: list[str] | None = None,
) -> Path:
    """Write the final Markdown report with a canonical site backlink."""

    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [
        "# Odisseo Signal Atlas",
        "",
        f"Official report generated by [Ulisses Flores]({site_url}).",
        "",
        f"**Generated at:** {datetime.now().isoformat(timespec='seconds')}",
        f"**Run status:** {run_status}",
        f"**Total repositories:** {len(repos)}",
        f"**Canonical site:** {site_url}",
        "",
        (
            "Format: GitHub link, stars, primary language, short description, "
            "and a strict disruption rationale."
        ),
        "",
    ]

    if stats:
        for label, value in stats.items():
            lines.append(f"**{label}:** {value}")
        lines.append("")

    if notes:
        lines.append("## Run notes")
        lines.append("")
        for note in notes:
            lines.append(f"- {note}")
        lines.append("")

    if not repos:
        lines.extend(
            [
                "No enriched repositories are available in this snapshot yet.",
                "",
            ]
        )

    for index, repo in enumerate(repos, start=1):
        stars = f"~{repo.stars}" if repo.stars else "new / low stars"
        language = repo.primary_language or "unknown"
        description = compact_text(repo.description or "No description.", max_length=180)
        lines.extend(
            [
                f"## {index}. {repo.repo_slug}",
                f"1. **Full GitHub link:** {repo.repo_url}",
                f"2. **Approximate stars:** {stars}",
                f"3. **Primary repository language:** {language}",
                f"4. **Short description:** {description}",
                f"5. **Why it is disruptive / frontier-grade:** {repo.rationale}",
                "",
                f"**Discovery languages:** {', '.join(repo.source_languages) or 'n/a'}",
                f"**Detected topics:** {', '.join(repo.matched_topics) or 'n/a'}",
                "",
            ]
        )

    output_path.write_text("\n".join(lines), encoding="utf-8")
    return output_path
