from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any, cast

import pytest

from odisseo_signal_atlas.config import Settings
from odisseo_signal_atlas.exceptions import OdisseoError
from odisseo_signal_atlas.github_client import GitHubClient
from odisseo_signal_atlas.models import SearchLanguage
from odisseo_signal_atlas.repo_inspector import RepoInspector


class DummyInspectorGitHubClient:
    def fetch_repo(self, owner: str, repo: str) -> dict[str, Any]:
        return {
            "html_url": f"https://github.com/{owner}/{repo}",
            "stargazers_count": 77,
            "language": "Python",
            "description": "Frontier MCP memory stack.",
            "topics": ["mcp", "memory", "agents"],
            "updated_at": "2026-03-19T00:00:00Z",
            "pushed_at": "2026-03-18T00:00:00Z",
            "homepage": "https://ulissesflores.com",
            "default_branch": "main",
            "license": {"name": "MIT"},
            "open_issues_count": 3,
            "forks_count": 4,
            "archived": False,
        }

    def fetch_readme(self, owner: str, repo: str) -> str:
        return "# Atlas\nMemory, agent orchestration, MCP hooks, voice RAG."

    def fetch_languages(self, owner: str, repo: str) -> dict[str, int]:
        return {"Python": 1500, "TypeScript": 300}

    def close(self) -> None:
        return None


def _settings(tmp_path: Path) -> Settings:
    return Settings(
        app_name="Odisseo Signal Atlas",
        environment="test",
        project_root=tmp_path,
        cache_dir=tmp_path / "cache",
        output_dir=tmp_path / "output",
        output_file=tmp_path / "output" / "report.md",
        repo_insights_dir=tmp_path / "output" / "repo-insights",
        site_url="https://ulissesflores.com",
        x_bearer_token="",
        github_token=None,
        x_search_endpoint="https://api.x.com/2/tweets/search/recent",
        x_max_results_per_page=100,
        x_pages_per_query=5,
        x_min_request_interval_seconds=0.0,
        x_lookback_days=1,
        x_max_backfill_days=1,
        x_window_hours=12,
        x_refresh_live_window=True,
        x_rate_limit_default_wait_seconds=60,
        x_rate_limit_max_wait_seconds=900,
        target_repos=500,
        candidate_target_multiplier=1.15,
        query_history_file=tmp_path / "cache" / "query_history.json",
        inspection_state_file=tmp_path / "cache" / "inspection_state.json",
        query_history_retention_days=30,
        excluded_repos=set(),
        search_languages=[SearchLanguage("en", "English", ("Claude Code",), ("memory",))],
    )


def test_inspect_next_writes_markdown_and_updates_state(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.cache_dir.mkdir(parents=True, exist_ok=True)
    (settings.cache_dir / "ranked.json").write_text(
        json.dumps(
            [
                {
                    "repo_url": "https://github.com/acme/atlas",
                    "repo_slug": "acme/atlas",
                    "stars": 77,
                    "primary_language": "Python",
                    "description": "Frontier MCP memory stack.",
                    "topics": ["mcp", "memory", "agents"],
                    "html_url": "https://github.com/acme/atlas",
                    "updated_at": "2026-03-19T00:00:00+00:00",
                    "pushed_at": "2026-03-18T00:00:00+00:00",
                    "source_languages": ["en", "ja"],
                    "matched_topics": ["memory", "protocols"],
                    "source_tweets": [],
                    "score": 10.0,
                    "rationale": "Signals detected: hidden gem.",
                }
            ]
        ),
        encoding="utf-8",
    )

    inspector = RepoInspector(settings)
    inspector.github_client = cast(GitHubClient, DummyInspectorGitHubClient())

    report = inspector.inspect_next()

    output = Path(report.output_path)
    assert report.repo_slug == "acme/atlas"
    assert report.source_cache == "ranked"
    assert output.exists()
    content = output.read_text(encoding="utf-8")
    assert "# Repo Investigation: acme/atlas" in content
    assert "Generated by [Ulisses Flores](https://ulissesflores.com)." in content
    assert "README flags:" in content
    state = json.loads(settings.inspection_state_file.read_text(encoding="utf-8"))
    assert "acme/atlas" in state["completed"]


def test_inspect_repo_supports_direct_slug_outside_ranked_cache(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    inspector = RepoInspector(settings)
    inspector.github_client = cast(GitHubClient, DummyInspectorGitHubClient())

    report = inspector.inspect_repo("acme/direct-atlas")

    assert report.repo_slug == "acme/direct-atlas"
    assert report.source_cache == "direct"
    assert Path(report.output_path).exists()


def test_inspect_next_raises_when_everything_was_already_processed(tmp_path: Path) -> None:
    settings = _settings(tmp_path)
    settings.cache_dir.mkdir(parents=True, exist_ok=True)
    (settings.cache_dir / "ranked.json").write_text(
        json.dumps(
            [
                {
                    "repo_url": "https://github.com/acme/atlas",
                    "repo_slug": "acme/atlas",
                    "stars": 77,
                    "primary_language": "Python",
                    "description": "Frontier MCP memory stack.",
                    "topics": ["mcp"],
                    "html_url": "https://github.com/acme/atlas",
                    "updated_at": "2026-03-19T00:00:00+00:00",
                    "pushed_at": "2026-03-18T00:00:00+00:00",
                    "source_languages": ["en"],
                    "matched_topics": ["memory"],
                    "source_tweets": [],
                    "score": 10.0,
                    "rationale": "Signals detected: hidden gem.",
                }
            ]
        ),
        encoding="utf-8",
    )
    settings.inspection_state_file.parent.mkdir(parents=True, exist_ok=True)
    settings.inspection_state_file.write_text(
        json.dumps(
            {
                "completed": {
                    "acme/atlas": {
                        "output_path": "output/repo-insights/acme--atlas.md",
                        "analyzed_at": datetime.now(UTC).isoformat(),
                        "source_cache": "ranked",
                    }
                }
            }
        ),
        encoding="utf-8",
    )

    inspector = RepoInspector(settings)
    inspector.github_client = cast(GitHubClient, DummyInspectorGitHubClient())

    with pytest.raises(OdisseoError, match="already been inspected"):
        inspector.inspect_next()
